name: "infra preview & test"

on:
  push:
    branches:
      - main
      - feature-webser-and-localenv
    paths:
      - webserver/**
      - .github/workflows/**

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Chrome
        run: |
          sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo apt update
          sudo apt-get install google-chrome-stable

      - name: Launching the Docker Container
        run: |
          docker-compose up -d

      - name: Running Tests
        run: |
          docker-compose run web npm run test

