name: "infra preview & test"

on:
  push:
    branches:
      - main
      - feature-webser-and-localenv
    paths:
      - webserver/**
      - .github/workflows/**

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cypress-io/github-action@v6

      - name: Launching the Docker Container
        run: |
          docker-compose up -d

      - name: Running Tests
        run: |
          docker-compose run web npm run test

